### ISSUE TITLE
Ook acteurs vermelden per serie?

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Android#104]
1. Zou het ook niet tof zijn om alle acteurs te tonen op elke serie en gastacteurs voor een episode? 
2. Indien je op die persoon klikt, zie je alle series waarin hij/zij in meespeelt.

**Comment by ExCellRaD** [comment]
👎 Persoonlijk zie ik er het nut niet echt van in (in de context van ons project). Tenzij die acteurs ook een profile hebben met achievements / hun favoriete series bekijken. Je kan altijd op IMDB gaan en daar de acteurs bekijken.

**Comment by HeinPauwelyn** [comment]
Acteurs hoeven niet per see een account hebben. op IMDb hebben acteurs ook geen account.

**Comment by ExCellRaD** [comment]
Ja dat bedoel ik ook, we maken geen informatie app he.

**Comment by HeinPauwelyn** [comment]
Ik vind het altijd tof om te weten elk personage in het echt is. Zo kan je bv. zeggen:

- "Ik heb die nog zien spelen maar ik weet niet in wat."
- "Ach deze acteur speelt ook mee in een ander programma." acteurs spelen meestal mee in hetzelfde genre als andere series. Is ook een mogelijkheid om nieuwe series te ontdekken.

**Comment by HeinPauwelyn** [comment]
puntje 2 kunnen we mss laten vallen maar dat eerste vind ik wel tof.

**Comment by ExCellRaD** [comment]
puntje 2 is juist het interessantst.

**Comment by HeinPauwelyn** [comment]
hoezo

**Comment by ExCellRaD** [comment]
door de  mogelijkheid om nieuwe series te ontdekken

**Comment by HeinPauwelyn** [comment]
mmmmmmmmmmm ja mss maar dan moet dat eerste er ook in vind ik zodat je de acteurs kunt vinden op basis van een serie dat jij al bekeken hebt.

**Comment by HeinPauwelyn** [comment]
Laten we de mening van @nielsbril en @mickverm ook meetellen. Het is niet goed als zijn niet mee mogen beslissen

**Comment by ExCellRaD** [comment]
Ik snap dat je dit wel iets handig vindt, ik vind dat ook, maar hoe past het in onze app? Dat is de eerste vraag die we moeten stellen. We willen niet gewoon een app maken om details van series te bekijken.

**Comment by ExCellRaD** [comment]
> Laten we de mening van @nielsbril en @mickverm ook meetellen. Het is niet goed als zijn niet mee mogen beslissen
Er is toch nog geen beslissing genomen? Dit is een discussie he :p

**Comment by HeinPauwelyn** [comment]
true

**Comment by nielsbril** [comment]
Denk dat ik me ga aansluiten bij @ExCellRaD, zie er niet echt een meerwaarde in, is misschien iets om te voorzien op het einde als er tijd over is, maar denk da met een link naar IMDB genoeg informatie te vinden is

**Comment by HeinPauwelyn** [comment]
Mss knop toevoegen waarbij je laat zeggen "ik ben figurant".

**Comment by ExCellRaD** [comment]
Op een serie? Ik ben niet goed mee.

**Comment by HeinPauwelyn** [comment]
Aflevering maar is gemakkelijk om dan te gaan vals spelen. Vergeet wat ik gezegd heb.

**Comment by HeinPauwelyn** [comment]
Slecht idee laat maar

-----------

Ben wel voorstander van muntje één:

> Enkele acteurs te tonen op elke serie en gastacteurs voor een episode?

Ook omdat je rapper weet wie erin meespeelt

Over puntje twee:

> Indien je op die persoon klikt, zie je alle series waarin hij/zij in meespeelt.

Past inderdaad niet echt in onze app
