### ISSUE TITLE
Permissions: library

### ISSUE THREAD

**Issue by nielsbril** [WatchFriends/Android#126]
Uitschrijven van code voor permissions is nogal lastig en repititief, ik heb volgende library gebruikt
Deze is zeer eenvoudig, met wat copy paste werk ben je er al, en wordt door heel wat mensen gebruikt

https://github.com/hotchemi/PermissionsDispatcher

Best eens bekijken dus ;)

**Comment by HeinPauwelyn** [comment]
Nog even zeggen dat het lastiger is geworden voor Marshmallow.

### Nota's

- [Check cursus Walcarius vorig jaar](https://1drv.ms/p/s!ApGaXS3n8HKUs0HeOFwZI3J0wfcw)
- Is inderdaad wel lastig ook als je rekening moet houden met API levels vanaf 19 (KitKat)
- Zeker ook eens uittesten op KitKat of Lollipop _(eventueel Ice Cream Sandwich, Gingerbread of Froyo)_.

### Vraag

- Welke (gevaarlijke) privileges moeten er wel toegelaten worden?

**Comment by nielsbril** [comment]
@HeinPauwelyn Inderdaad, maar dit handelt net alles af voor u, ongeacht of het API 23 of lager is. Gevaarlijke priviliges zijn er nog niet zo heel veel, ik had ééntje nodig om accounts te managen (aka inloggen)
