### ISSUE TITLE
PreferenceFragment

### ISSUE THREAD

**Issue by nielsbril** [WatchFriends/Android#127]
Aanmaken van settings voor user

**Comment by HeinPauwelyn** [comment]
Mss nog een instelling van de gebruiken is de taal die ze wensen. Later ga ik de lijsten op de home pagina daarvan laten afhangen. _(zie https://github.com/WatchFriends/Web/issues/74#issuecomment-267567381)_

**Comment by HeinPauwelyn** [comment]
Een extra instelling is volgende: _"Log off on all devices"_. Zie https://github.com/WatchFriends/Web/issues/107
