### ISSUE TITLE
Aantal lijsten verminderen

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Android#128]
Momenteel hebben we vijf lijsten;

  - Watched _(Heb het bekeken)_
  - Wachting _(Aan het bekijken)_
  - Watchlist _(Ga het bekijken)_
  - Following _(Deze serie wil ik volgen)_
  - Favorieten

Dit wil ik verminderen naar twee direct zichtbaar en één onzichtbaare lijsten

- Zichtbaar
  - Watched _(Heb ik bekeken)_
  - Watchlist _(Ga ik bekijken)_
- Onzichtbaar
  - Following _(Aan het volgen)_

Indien je één van de episodes toevoegd aan _watched_ of _watchlist_ volg je automatisch de volledige serie. Je hebt nog wel de kans op dit opnieuw uit te zetten indien de serie je niet bevalt, vandaar de derde lijst _following_.

De lijst _watching_ mag weg omdat iedere ~~serie~~ episode er toch maar maximaal een uur zal instaan en het zeer vervelend is voor ieder uur dit te gaan aanpassen als je een marathon van episodes of seizoenen bekijkt.

De lijst _following_ moet toch nog aangemaakt worden voor technische redenen. Indien je de serie niet meer volgt verdwijnt hij uit de lijst. De reden waarom hij "onzichtbaar" is, is omdat dit niet de bedoeling is om dit als lijst weer te geven. Indien de gebruiker op een serie terecht komt, krijgt hij/zij de kans op dit toe te voegen of te verwijderen uit de lijst.

_Favorieten_ (weet niet wie er op dat idee kwam maar werd wel al eens gezegd dat we dat gingen doen) mag weg voor de volgende simpele reden: als je een serie volgt wil dat zeggen dat dit één van je favorieten zijn en is dus overbodig om een lijst speciaal daarvoor aan te maken.

Voor andere twee lijsten worden enkel de ID's van de afleveringen bijgehouden. Als je privé modus wilt, komt er een extra kolom in de database met een `boolean`: mag dit aan iedereen getoond worden (= `true`) of niet (= `false`).

Reacties hieronder

**Comment by ExCellRaD** [comment]
Dus eigenlijk watching hernoemen naar following en onzichtbaar maken? En watched en watchlist er aan toevoegen?

**Comment by HeinPauwelyn** [comment]
> Dus eigenlijk watching hernoemen naar following en onzichtbaar maken?

Nee watching moet weg en following onzichtbaar<sup>1</sup> maken door de volgende reden:

> De lijst watching mag weg omdat iedere ~~serie~~ _(ik bedoelde)_ episode er toch maar maximaal een uur zal instaan en het zeer vervelend is voor ieder uur dit te gaan aanpassen als je een marathon van episodes of seizoenen bekijkt.



> En watched en watchlist er aan toevoegen?

Die lijsten blijven onveranderd. Nog even voor de duidelijkheid: enkel ID's van episodes komen erin opgelijst.

<sup><sup>1</sup> Je kan die lijst niet vinden via de navigation drawer, noch de start pagina, noch alle andere fragmenten. Dit is gewoon een lijst om het ons gemakkelijker te maken. Tenzij je nog andere ideeën hebt.</sup>

**Comment by HeinPauwelyn** [comment]
**Besluit**

Twee lijsten:

- Series die je volgt
- Afleveringen bekeken
