### ISSUE TITLE
SettingsFragment: only first preference shown

### ISSUE THREAD

**Issue by nielsbril** [WatchFriends/Android#143]
[https://stackoverflow.com/questions/41171735/android-preferencefragment-only-showing-first-preference](https://stackoverflow.com/questions/41171735/android-preferencefragment-only-showing-first-preference)

Nog niet meteen iets gevonden die wel werkt :(

**Comment by HeinPauwelyn** [comment]
Waarom gebruik je geen twee `SwitchPreference` elementen?

**Comment by nielsbril** [comment]
Maakt geen verschil uit, onafhankelijk van wat er in de file staat, wordt enkel en alleen de eerste preference getoond. Heb echt geen idee waarom.

**Comment by HeinPauwelyn** [comment]
Zie SO er is een antwoord plaatst

**Comment by HeinPauwelyn** [comment]
Is het al opgelost?
