### ISSUE TITLE
API request aanpassen naar watchfriends API

### ISSUE THREAD

**Issue by mickverm** [WatchFriends/Android#159]

**Comment by HeinPauwelyn** [comment]
Rekening houden met: https://github.com/WatchFriends/Web/pull/83

**Comment by mickverm** [comment]
Ben hiermee klaar maar zal wachten tot de spelfoutenfix gedeployed word naar watchfriends.me anders zal de app voortdurend crashen

**Comment by HeinPauwelyn** [comment]
Dat zou automatisch moeten werken vind ik. Telkens als er een nieuwe release is ofzo. 

@nielsbril Heb je al geken als je uw server kunt integreren met GitHub?

**Comment by ExCellRaD** [comment]
@mickverm kan je al eens een PR maken met wat je al hebt?
