### ISSUE TITLE
Token sturen van & naar backend ☠

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Android#163]
Er moet voor de Android applicatie een token verzonden worden voor te weten wie er aangemeld is voor de juiste data te gaan opslaan voor te series te volgen, achievements te krijgen of profiel pagina.

1. Moet dit nog geïmplementeerd worden op de backend?
   - Indien ja door wie en wanneer. Ken jezelf toe aan deze issue.
   - Indien nee zal ik wel voor kijken.
2. Is er al iemand me bezig?
   - Indien ja door wie en wanneer. Ken jezelf toe aan deze issue en doe maar voort.
   - Indien nee zal ik wel voor kijken.

Zie ook: https://github.com/WatchFriends/Web/issues/107

**Comment by ExCellRaD** [comment]
token in requests meesturen op een van deze manieren:
- in form body of URLencoded (access_token)
- in querystring (access_token)
- in header field (Authorization header met daarin Bearer en dan token)
http://self-issued.info/docs/draft-ietf-oauth-v2-bearer.html
