### ISSUE TITLE
Sociale providers inloggen

### ISSUE THREAD

**Issue by JasperDeSutter** [WatchFriends/Android#169]
Facebook en google authenticatie als login-methode uitwerken

**Comment by JasperDeSutter** [comment]
Ik ga hiermee even stoppen, zodat ik nog aan andere dingen kan werken. Een paar problemen zijn:
- Google is goed gedocumenteerd, maar facebook niet
- We hebben geen access aan facebook en google in backend (kan dus niet testen)
- De logica van de callback (die normaal door facebook en google zelf gemaakt wordt) moeten wij nu zelf maken en sturen naar de backend, en om dit na te maken moet ik kunnen testen.

**Comment by HeinPauwelyn** [comment]
sluiten?
