### ISSUE TITLE
Bug Home

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Android#173]
Er is een bug op de home fragment en vind hem niet direct. Kan je me helpen? 

![image](https://cloud.githubusercontent.com/assets/16222780/22329262/cb4208f8-e3c0-11e6-9e71-e1ce4a5bc87e.png)

**Comment by mickverm** [comment]
Ik krijg voortdurend Unauthorized op home waardoor de app crasht

**Comment by HeinPauwelyn** [comment]
Was dat niet die het probleem gaf. De lijsten _(titels en series die je in screenshot ziet)_ worden dynamisch geladen. d.w.z. als er nu een vierde lijst bijkomt, wordt hij ook ingeladen in deze ingeladen. Het was `results` die null was in de `SeriesList` object.

Het probleem is ondertussen opgelost door `results` te vervangen door `series`.
