### ISSUE TITLE
Presentatie

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Android#176]

**Comment by HeinPauwelyn** [comment]
@nielsbril Wat er zeker in de presentatie moet is de 3<sup>de</sup> slide van [ de front- en back-end presentatie](https://github.com/WatchFriends/Android/files/732360/Presentatie.Frontend.pptx)

![image](https://cloud.githubusercontent.com/assets/16222780/22332883/6e70da2e-e3d3-11e6-9c9a-c2427cb8e43d.png)

Vervang dan wel de term middleware door API, was een opmerking Johan had.

**Comment by nielsbril** [comment]
komt in orde :)

**Comment by nielsbril** [comment]
iemand vrijwilliger om de demo uit te voeren? deze persoon moet dan niets van de slides 'presenteren'

**Comment by nielsbril** [comment]
[Presentatie.pptx](https://github.com/WatchFriends/Android/files/732638/Presentatie.pptx)

hier de presentatie, is ongeveer af (nog hier en daar screenshot aanpassen & link naar video aanpassen), feedback welkom

ik stel voor om het zo te verdelen
- persoon 1: dia 1 - 5 (concept en dergelijke)(ik zie dit wel zitten)
- persoon 2: dia 6 - 16 (overlopen wireframes & hun realisatie)
- persoon 3: dia 17 - 23 (wbs, source control, positief, negatief) (ik wil gerust nog een deeltje hiervan nemen naast die dia 1 - 5)
- persoon 4: demo

**Comment by HeinPauwelyn** [comment]
Kan je de presentatie eens commiten? Er zijn wat netwerkfouten.

**Comment by nielsbril** [comment]
PR geplaatst

**Comment by HeinPauwelyn** [comment]
* Dia 9 is de wireframe voor windows denk ik.
* Dia 16 is wireframe verkeerd
* Dia 20 is een beetje teveel tekst denk ik.
* Dia 21 kan de contributions van jasper en excellrad onder elkaar staan. hoeveel hij gedaan heeft.
* Promovideo mag op eerste dia en graag toevoegen aan de ppt zelf. Is proffesioneler.

**Comment by nielsbril** [comment]
na ik de promovideo af heb kijk ik hier nog voor! over de opmerking omtrent wireframes in de dia's -> is een vereiste van walcarius

**Comment by HeinPauwelyn** [comment]
als het verplicht is, heb ik geen problemen
