### ISSUE TITLE
home page temporary bug

### ISSUE THREAD

**Issue by nielsbril** [WatchFriends/Android#177]
Na mergen van mijn pull request zal home page terug niet meer werken, aangezien in die code de api call in homefragmentviewmodel in commentaar stond. Best dus iemand van jullie in een volgende pull request dit opnieuw uit commentaar halen & committen

**Comment by HeinPauwelyn** [comment]
Eerst code die niet weg mag zelf weg doen zal in het vervolg helpen 😄

**Comment by nielsbril** [comment]
mijn excuses, maar had dit gistern weggedaan om zelf te kunnen werken zonder dat de app crasht bij startup :p daarna vergeten weg te doen

**Comment by HeinPauwelyn** [comment]
Is niets 😄

**Comment by HeinPauwelyn** [comment]
wil je #178 goedkeuren?

**Comment by nielsbril** [comment]
gedaan & gemerged
