### ISSUE TITLE
Series Id in EpisodeFragment

### ISSUE THREAD

**Issue by mickverm** [WatchFriends/Android#179]
Weet iemand of en hoe het mogelijk is om het ID van de serie op te halen binnen een episodefragment?

**Comment by JasperDeSutter** [comment]
Dit kan nu nog niet, dat komt doordat het nog niet juist wordt meegegeven aan de episode.
De newInstance methode krijgt nu enkel een EpisodeFragment binnen, maar zou ook series ID en season ID moeten krijgen (zoals dat SeasonFragment ook series ID krijgt via newInstance)

**Comment by mickverm** [comment]
ok, zal dit dus nog moeten schrijven, maar @JasperDeSutter seasonId komt al mee in het episodeobject, dus gewoon seriesId moet nog doorgegeven worden

**Comment by mickverm** [comment]
Hmmm, de seriesId moet op 1 of andere manier in de episodesadapter geraken

**Comment by JasperDeSutter** [comment]
SeriesId meegeven aan de episodesadapter, die het dan meegeeft in onclick aan mainactivity onEpisodeSelected
