### ISSUE TITLE
Homepage herlaadt na rotatie

### ISSUE THREAD

**Issue by JasperDeSutter** [WatchFriends/Android#181]
Iedere keer dat je de orientatie verandert gaat de homepage opnieuw api calls doen om de lijsten op te halen. Waarschijnlijk de loadlists code die in een verkeerde functie staat.

**Comment by nielsbril** [comment]
Android herstart activities / fragments bij herorientatie, dus wordt dit sowieso opnieuw opgeroepen, moet eigenlijk opgelost worden door de state van het fragment te bewaren in onStop (of hoe die methode ook heet) en dit werd al enige tijd geleden toegewezen aan jou als taak

**Comment by mickverm** [comment]
https://github.com/WatchFriends/Android/issues/130

**Comment by JasperDeSutter** [comment]
@nielsbril 
Ja maar de code om api calls te doen staan op de meeste plaatsen in de viewmodels, en deze worden gewoon iedere keer aangeroepen als ze aangemaakt worden. Dit is dus niet echt aanpasbaar vanuit de fragments zelf. 
EpisodeFragment is de enigste die dit juist doet ATM, maar dat is omdat deze fragment het Episode object meekrijgt in newInstance()

> #130 
Andere issue, deze gaat over het herladen van de data, 130 gaat erover dat je altijd weer naar home gaat.

**Comment by nielsbril** [comment]
verkeerd begrepen dan, maar sowieso denk ik dat bij herorientatie alles opnieuw uitgevoerd zal worden indien je de data niet opslaat via de state

**Comment by JasperDeSutter** [comment]
@HeinPauwelyn Ik heb het al gevonden en gefixt.
