### ISSUE TITLE
UserID

### ISSUE THREAD

**Issue by mickverm** [WatchFriends/Android#188]
Hoe kan ik de UserId van de ingelogde gebruiker krijgen? heb deze nodig om in de syncmanager alle gevolgde series op te halven van de backend.

**Comment by HeinPauwelyn** [comment]
en ik voor de achievements op de profiel pagina

**Comment by JasperDeSutter** [comment]
Probeer eens null, de userId is niet verplicht in backend. Als dit niet lukt gewoon een extra api route aanmaken in de apiservice zonder de userId parameter.
