### ISSUE TITLE
SQLite error

### ISSUE THREAD

**Issue by JasperDeSutter** [WatchFriends/Android#189]
01-26 20:44:42.021 9860-9860/nmct.jaspernielsmichielhein.watchfriends E/SQLiteLog: (1) no such column: following
01-26 20:44:42.024 9860-9860/nmct.jaspernielsmichielhein.watchfriends E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        Process: nmct.jaspernielsmichielhein.watchfriends, PID: 9860

Heb ik nog een verouderde versie van de database of zo? Hoe los ik dit op? @mickverm

**Comment by mickverm** [comment]
App verwijderen en opnieuw installeren, heb geprobeerd een update script te schrijven maar ging niet en wou niet teveel tijd verliezen
 zie https://github.com/WatchFriends/Android/pull/185

**Comment by JasperDeSutter** [comment]
Sorry ik had dat niet gelezen, werkt nu helemaal!
