### ISSUE TITLE
Feedback Stijn Walcarius Wireframes

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Android#47]
- goed uitgewerkt
- home pagina voor zijdelings scrollen
  - @walcariuss gaat nog link doorsturen
  - had ander idee
- watchlist
  - reden waarom geen tabbladen bij Android?
- material design gebruiken op elke wireframes.
- season
  - dividers &rarr; op een frame verschillende stukjes tonen
  - scrollable layout
- settings
  - vraagt veel meer
# algemeen
- zoveel mogelijk material design

**Comment by ExCellRaD** [comment]
> dividers op een frame verschillende stukjes tonen

wat exact wordt hiermee bedoeld?

**Comment by HeinPauwelyn** [comment]
ge moet ne kje hoehel'n é. dit is iere: https://material.google.com/components/dividers.html

**Comment by mickverm** [comment]
https://material.google.com/components/dividers.html#dividers-usage

**Comment by HeinPauwelyn** [comment]
Antwoord van Stijn Walcarius via e-mail:

> Dag Hein,

> Voor jullie project zal je wellicht een horizontal recycleview nodig hebben. Je vindt online veel voorbeelden, maar het ultieme voorbeeld dat het dichtst aansluit op jouw vraag heb ik nog niet gevonden.

> Op eerste zicht interessant lijkt mij:

> * http://www.androhub.com/android-staggered-and-horizontal-recyclerview/ 
> * http://www.questdot.com/android-image-gallery-horizontalscrollview-tutorial/ 

> Sowieso wordt het wat uitproberen.

> Vriendelijke groeten,

> Stijn Walcarius
