### ISSUE TITLE
Onderzoek API

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Android#48]
- TVDB
- ...

**Comment by nielsbril** [comment]
Twee API's onderzocht: TVDB & MoviesDB. Twee keer identiek hetzelfde ongeveer, MoviesDB ondersteunt ook films.

Authenticatie bij MoviesDB is wel makkelijker: enkel een API key meegeven, terwijl bij TVDB gewerkt wordt met een token die aangevraagd moet worden en meegestuurd worden met de HTTP headers.

Documentatie is terug te vinden op: [https://developers.themoviedb.org/3/getting-started](MoviesDB API Reference)

Voor account & API key: zie OneDrive.
