### ISSUE TITLE
series detail fragment

### ISSUE THREAD

**Issue by ExCellRaD** [WatchFriends/Android#72]
- [x] viewmodel maken
- [x] viewmodel binden
- [x] adapter voor seasons
- [x] SeasonSelectedListener (implementeren in MainActivity -> navigate(new SeasonFragment))
- [x] dummy season list (in view/dummy)
- [x] season_item layout
- [x] fragment_series layout
- [x] eventueel season_list layout apart

**Comment by nielsbril** [comment]
Zal nu even hieraan werken (viewmodel + api + fragment en daarna view)
