### ISSUE TITLE
package ....databinding does not exist

### ISSUE THREAD

**Issue by HeinPauwelyn** [WatchFriends/Android#90]
zie commit https://github.com/WatchFriends/Android/commit/73829070f99def7b4e913c37e309fe8c06a5bd7b

error message:

> **error:** package `nmct.jaspernielsmichielhein.watchfriends.databinding` does not exist

Wat heb ik gedaan?

```xml
<ListView android:id="@+id/id_gallery"
          android:layout_width="wrap_content"
          android:layout_height="400px"
          android:layout_gravity="center_vertical"
          android:scrollbars="horizontal"
          app:items="@{ viewModel.recommendedByFriends }" />
```

Bovenstaande code toegevoegd in `home_fragment.xml`.

Meer info zie de branch [`home`](https://github.com/WatchFriends/Android/tree/home).

Indie je commit wilt doen, maak een eigen branch aan beginnende van de `home` branch en doe een pull request naar de `home` branch i.p.v. de `master` branch.

**Comment by nielsbril** [comment]
fixed it ;)

**Comment by HeinPauwelyn** [comment]
Commit: https://github.com/WatchFriends/Android/commit/006769615b8fa494ad79140e8d72f3c9ed262af6

Vrag op SO: http://stackoverflow.com/questions/40440662/databinding-does-not-exist-how-to-solve-it

**Comment by nielsbril** [comment]
Fixed, zie branch `devHome-Niels`, komt omdat binder, adapter, enzovoort andere zaken nodig hebben tov van een listview

**Comment by HeinPauwelyn** [comment]
Is het al gesynct met GitHub.com wat ik zie hier nog niets.

**Comment by nielsbril** [comment]
nu wel, mijn excuses

**Comment by HeinPauwelyn** [comment]
pfff voel me dom :confused: 

Weet van langs geen kanten wat ik verkeerd doe

**Comment by nielsbril** [comment]
is gewoon een kwestie van vertrouwd raken met DataBinding, zijn demo's zijn goede voorbeelden voor wat er nodig is in welk geval (listview, recyclerview, ...)

ook altijd zorgen voor getters & setters, aangezien DataBinding deze gebruikt om de value op te halen en bij twoway binding de value in te stellen
